config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  
  resources :posts

  resources :topics

  resources :forums

  resources :games

  get 'profiles/show'

  get "games/match"

  get 'static_pages/about'

 resources :users

  get 'welcome/index'

   root 'welcome#index'

   get '/about' => 'static_pages#about'
   get '/contact' => 'static_pages#contact'
   get '/gamers' => 'static_pages#gamers'
   get '/calendar' => 'static_pages#calendar'
   get '/statuses' => 'static_pages#statuses'

   controller :sessions do
    get "login" => "sessions#new"
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
  end

  get 'users/:id' => 'users#show'

  get '/:id', to: 'profiles#show'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :topics, :dependent => :destroy
	belongs_to :user, :dependent => :destroy
	has_many :posts, :dependent => :destroy
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]

  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
     # @forum = Forum.new(forum_params) 
     @forum = current_user.forums.new(forum_params)

     #@forum = current_user.forum.build(forum_params) 

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url, notice: 'Forum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:name, :description, :user_id)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= bootstrap_form_for(@forum) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  
<% end %>

app/views/forums/edit.html.erb
<h1>Editing forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<div class="container">

<h1> Forums </h1>

<h4 class="coming-soon">Coming soon!</h4>


<!--  
<table class="table table-striped">
  <tr>
    <th class="col-md-7">Forum</th>
    <th class="col-md-5">Last Post</th>
  </tr>
<!--   <% for forum in @forums %>
 -->    <tr>
      <td><h2><%= link_to h(forum.name), forum_path(forum.id) %></h2>
        <small><%= forum.topics.count %> topics</small><br />
        <%= forum.description %></td>
      <td class="right"></td>
      <td><%= link_to "Show", forum %></td>
      <td><%= link_to "Edit", edit_forum_path(forum) %></td>
      <td><%= link_to "Destroy", forum, :confirm => 'Yeah?', :method => :delete %></td>
    </tr>
<!--   <% end %>
 --></table> 
 <!-- 
<p style="padding-top:2em;"><%= link_to "New Forum", new_forum_path, :class => "btn btn-info" %></p> -->
</div>

app/views/forums/new.html.erb
<div class="container">
<h1>New forum</h1>

<%= render 'form' %>

<%= link_to 'Back', forums_path %>
</div>

app/views/forums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @forum.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @forum.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @forum.user_id %>
</p>

<%= link_to 'Edit', edit_forum_path(@forum) %> |
<%= link_to 'Back', forums_path %>