config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  
  resources :posts

  resources :topics

  resources :forums

  resources :games

  get 'profiles/show'

  get "games/match"

  get 'static_pages/about'

 resources :users

  get 'welcome/index'

   root 'welcome#index'

   get '/about' => 'static_pages#about'
   get '/contact' => 'static_pages#contact'
   get '/gamers' => 'static_pages#gamers'
   get '/calendar' => 'static_pages#calendar'
   get '/statuses' => 'static_pages#statuses'

   controller :sessions do
    get "login" => "sessions#new"
    post "login" => "sessions#create"
    delete "logout" => "sessions#destroy"
  end

  get 'users/:id' => 'users#show'

  get '/:id', to: 'profiles#show'

end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basem3nt</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= nav_bar :static => :top, :responsive => true, :brand => "Basem3nt", :class =>"navbar-fixed-top navbar ", :style => "color:#FFFFFF;" do %>
     <%= menu_group do %>
         <%= menu_item "HOME", root_path %>
        <%= menu_item "GAMES", games_path %>
        <%= menu_item "FORUMS", forums_path %>
        <%= menu_item "NEWSFEED", statuses_path %>

     <% end %>

    <% if current_user %>
      <div class="sign form-group hideS">
        <p><%= link_to current_user.gamertag, "#{current_user.gamertag}"
 %></p>
        <p><%= link_to "SETTING", edit_user_registration_path, method: :get, :class =>  "navbar-link, ../users/edit" %></p>
        <p><%= link_to "SIGN OUT", destroy_user_session_path, method: :delete, :class => 'navbar-link, logInLogOut' %></p>
      </div>

       <% else %>
        <%= menu_group :pull => :right do %>
           <!--  <%= bootstrap_form_for @user, :url => session_path(:user) do |f| -%>
              <div class="sign form-group">
                <p><%= f.email_field :email,  placeholder: "EMAIL", :class => "input", autofocus: true, hide_label: :true %>
                </p>
                <p><%= f.password_field :password, placeholder:"PASSWORD", :class=> "input", autocomplete: "off", hide_label: :true %>
                  </p>
                  <p><%= f.submit "SIGN IN", :class=>  'btn btn-xs btn-success' %>
                  </p>
                <% end -%>
                <p><%= link_to "SIGN UP", new_user_registration_path, :class=>  'btn btn-xs btn-primary' %>
                </p> -->
            <% end %>
        <% end %>
    <% end %>
    <%= bootstrap_flash %>
      <div class="mainBody">
        <div class="container">
       <%= yield %>      
     </div>
      </div>
<div class="col-md-12 footer">
  <div>AN <br> UNTAMED KILLER <br>WHALE PRODUCTION</div>
  </div> 
  </body>
</html>